export interface CuratedCompoundEntry {
  key: string
  query: string
  englishName: string
  koreanName: string
  aliases?: string[]
}

export const CURATED_COMPOUNDS: CuratedCompoundEntry[] = [
  { key: 'water', query: 'Water', englishName: 'Water', koreanName: '물', aliases: ['Oxidane'] },
  { key: 'hydrogen-peroxide', query: 'Hydrogen peroxide', englishName: 'Hydrogen peroxide', koreanName: '과산화수소' },
  { key: 'ammonia', query: 'Ammonia', englishName: 'Ammonia', koreanName: '암모니아' },
  { key: 'carbon-dioxide', query: 'Carbon dioxide', englishName: 'Carbon dioxide', koreanName: '이산화탄소' },
  { key: 'carbon-monoxide', query: 'Carbon monoxide', englishName: 'Carbon monoxide', koreanName: '일산화탄소' },
  { key: 'methane', query: 'Methane', englishName: 'Methane', koreanName: '메테인' },
  { key: 'ethane', query: 'Ethane', englishName: 'Ethane', koreanName: '에테인' },
  { key: 'propane', query: 'Propane', englishName: 'Propane', koreanName: '프로페인' },
  { key: 'butane', query: 'Butane', englishName: 'Butane', koreanName: '부테인' },
  { key: 'ozone', query: 'Ozone', englishName: 'Ozone', koreanName: '오존' },
  { key: 'ethylene', query: 'Ethylene', englishName: 'Ethylene', koreanName: '에틸렌', aliases: ['Ethene'] },
  { key: 'propylene', query: 'Propylene', englishName: 'Propylene', koreanName: '프로필렌', aliases: ['Propene'] },
  { key: 'acetylene', query: 'Acetylene', englishName: 'Acetylene', koreanName: '아세틸렌', aliases: ['Ethyne'] },
  { key: 'benzene', query: 'Benzene', englishName: 'Benzene', koreanName: '벤젠' },
  { key: 'toluene', query: 'Toluene', englishName: 'Toluene', koreanName: '톨루엔' },
  { key: 'phenol', query: 'Phenol', englishName: 'Phenol', koreanName: '페놀' },
  { key: 'acetone', query: 'Acetone', englishName: 'Acetone', koreanName: '아세톤' },
  { key: 'formaldehyde', query: 'Formaldehyde', englishName: 'Formaldehyde', koreanName: '포름알데히드', aliases: ['Methanal'] },
  { key: 'acetic-acid', query: 'Acetic acid', englishName: 'Acetic acid', koreanName: '아세트산', aliases: ['Ethanoic acid'] },
  { key: 'formic-acid', query: 'Formic acid', englishName: 'Formic acid', koreanName: '포름산', aliases: ['Methanoic acid'] },
  { key: 'citric-acid', query: 'Citric acid', englishName: 'Citric acid', koreanName: '구연산' },
  { key: 'lactic-acid', query: 'Lactic acid', englishName: 'Lactic acid', koreanName: '젖산' },
  { key: 'benzoic-acid', query: 'Benzoic acid', englishName: 'Benzoic acid', koreanName: '벤조산' },
  { key: 'salicylic-acid', query: 'Salicylic acid', englishName: 'Salicylic acid', koreanName: '살리실산' },
  { key: 'aspirin', query: 'Aspirin', englishName: 'Aspirin', koreanName: '아스피린', aliases: ['Acetylsalicylic acid'] },
  { key: 'acetaminophen', query: 'Acetaminophen', englishName: 'Acetaminophen', koreanName: '아세트아미노펜', aliases: ['Paracetamol'] },
  { key: 'ibuprofen', query: 'Ibuprofen', englishName: 'Ibuprofen', koreanName: '이부프로펜' },
  { key: 'caffeine', query: 'Caffeine', englishName: 'Caffeine', koreanName: '카페인' },
  { key: 'nicotine', query: 'Nicotine', englishName: 'Nicotine', koreanName: '니코틴' },
  { key: 'ethanol', query: 'Ethanol', englishName: 'Ethanol', koreanName: '에탄올' },
  { key: 'methanol', query: 'Methanol', englishName: 'Methanol', koreanName: '메탄올' },
  { key: 'isopropyl-alcohol', query: 'Isopropyl alcohol', englishName: 'Isopropyl alcohol', koreanName: '아이소프로필 알코올', aliases: ['Isopropanol', '2-Propanol'] },
  { key: 'glycerol', query: 'Glycerol', englishName: 'Glycerol', koreanName: '글리세롤', aliases: ['Glycerin'] },
  { key: 'ethylene-glycol', query: 'Ethylene glycol', englishName: 'Ethylene glycol', koreanName: '에틸렌글리콜' },
  { key: 'propylene-glycol', query: 'Propylene glycol', englishName: 'Propylene glycol', koreanName: '프로필렌글리콜' },
  { key: 'urea', query: 'Urea', englishName: 'Urea', koreanName: '요소' },
  { key: 'glucose', query: 'Glucose', englishName: 'Glucose', koreanName: '포도당', aliases: ['D-Glucose'] },
  { key: 'fructose', query: 'Fructose', englishName: 'Fructose', koreanName: '과당', aliases: ['D-Fructose'] },
  { key: 'sucrose', query: 'Sucrose', englishName: 'Sucrose', koreanName: '자당' },
  { key: 'lactose', query: 'Lactose', englishName: 'Lactose', koreanName: '유당' },
  { key: 'maltose', query: 'Maltose', englishName: 'Maltose', koreanName: '맥아당' },
  { key: 'niacinamide', query: 'Niacinamide', englishName: 'Niacinamide', koreanName: '나이아신아마이드', aliases: ['Nicotinamide'] },
  { key: 'biotin', query: 'Biotin', englishName: 'Biotin', koreanName: '비오틴', aliases: ['Vitamin B7'] },
  { key: 'retinol', query: 'Retinol', englishName: 'Retinol', koreanName: '레티놀', aliases: ['Vitamin A1'] },
  { key: 'sodium-chloride', query: 'Sodium chloride', englishName: 'Sodium chloride', koreanName: '염화나트륨' },
  { key: 'potassium-chloride', query: 'Potassium chloride', englishName: 'Potassium chloride', koreanName: '염화칼륨' },
  { key: 'calcium-carbonate', query: 'Calcium carbonate', englishName: 'Calcium carbonate', koreanName: '탄산칼슘' },
  { key: 'sodium-bicarbonate', query: 'Sodium bicarbonate', englishName: 'Sodium bicarbonate', koreanName: '탄산수소나트륨', aliases: ['Sodium hydrogen carbonate'] },
  { key: 'sodium-carbonate', query: 'Sodium carbonate', englishName: 'Sodium carbonate', koreanName: '탄산나트륨' },
  { key: 'calcium-chloride', query: 'Calcium chloride', englishName: 'Calcium chloride', koreanName: '염화칼슘' },
  { key: 'magnesium-sulfate', query: 'Magnesium sulfate', englishName: 'Magnesium sulfate', koreanName: '황산마그네슘' },
  { key: 'copper-sulfate', query: 'Copper sulfate', englishName: 'Copper sulfate', koreanName: '황산구리' },
  { key: 'sodium-hydroxide', query: 'Sodium hydroxide', englishName: 'Sodium hydroxide', koreanName: '수산화나트륨' },
  { key: 'potassium-hydroxide', query: 'Potassium hydroxide', englishName: 'Potassium hydroxide', koreanName: '수산화칼륨' },
  { key: 'hydrochloric-acid', query: 'Hydrochloric acid', englishName: 'Hydrochloric acid', koreanName: '염산' },
  { key: 'sulfuric-acid', query: 'Sulfuric acid', englishName: 'Sulfuric acid', koreanName: '황산' },
  { key: 'nitric-acid', query: 'Nitric acid', englishName: 'Nitric acid', koreanName: '질산' },
  { key: 'phosphoric-acid', query: 'Phosphoric acid', englishName: 'Phosphoric acid', koreanName: '인산' },
  { key: 'sodium-hypochlorite', query: 'Sodium hypochlorite', englishName: 'Sodium hypochlorite', koreanName: '차아염소산나트륨' },
  { key: 'silicon-dioxide', query: 'Silicon dioxide', englishName: 'Silicon dioxide', koreanName: '이산화규소', aliases: ['Silica'] },
  { key: 'aluminum-oxide', query: 'Aluminum oxide', englishName: 'Aluminum oxide', koreanName: '산화알루미늄' },
  { key: 'calcium-oxide', query: 'Calcium oxide', englishName: 'Calcium oxide', koreanName: '산화칼슘' },
  { key: 'ammonium-nitrate', query: 'Ammonium nitrate', englishName: 'Ammonium nitrate', koreanName: '질산암모늄' },
  { key: 'ammonium-sulfate', query: 'Ammonium sulfate', englishName: 'Ammonium sulfate', koreanName: '황산암모늄' },
  { key: 'sodium-nitrate', query: 'Sodium nitrate', englishName: 'Sodium nitrate', koreanName: '질산나트륨' },
  { key: 'potassium-nitrate', query: 'Potassium nitrate', englishName: 'Potassium nitrate', koreanName: '질산칼륨' },
  { key: 'monosodium-glutamate', query: 'Monosodium glutamate', englishName: 'Monosodium glutamate', koreanName: '글루탐산나트륨', aliases: ['L-Glutamic acid monosodium salt'] },
  { key: 'sodium-acetate', query: 'Sodium acetate', englishName: 'Sodium acetate', koreanName: '아세트산나트륨' },
  { key: 'sodium-citrate', query: 'Sodium citrate', englishName: 'Sodium citrate', koreanName: '구연산나트륨' },
  { key: 'potassium-sorbate', query: 'Potassium sorbate', englishName: 'Potassium sorbate', koreanName: '소르빈산칼륨' },
  { key: 'sodium-benzoate', query: 'Sodium benzoate', englishName: 'Sodium benzoate', koreanName: '벤조산나트륨' },
  { key: 'ascorbic-acid', query: 'Ascorbic acid', englishName: 'Ascorbic acid', koreanName: '아스코르브산', aliases: ['Vitamin C'] },
  { key: 'folic-acid', query: 'Folic acid', englishName: 'Folic acid', koreanName: '엽산', aliases: ['Vitamin B9'] },
  { key: 'aspartame', query: 'Aspartame', englishName: 'Aspartame', koreanName: '아스파탐' },
  { key: 'xylitol', query: 'Xylitol', englishName: 'Xylitol', koreanName: '자일리톨' },
  { key: 'sorbitol', query: 'Sorbitol', englishName: 'Sorbitol', koreanName: '소르비톨' },
  { key: 'vanillin', query: 'Vanillin', englishName: 'Vanillin', koreanName: '바닐린' },
  { key: 'cholesterol', query: 'Cholesterol', englishName: 'Cholesterol', koreanName: '콜레스테롤' },
  { key: 'taurine', query: 'Taurine', englishName: 'Taurine', koreanName: '타우린' },
  { key: 'creatine', query: 'Creatine', englishName: 'Creatine', koreanName: '크레아틴' },
  { key: 'uric-acid', query: 'Uric acid', englishName: 'Uric acid', koreanName: '요산' },
  { key: 'creatinine', query: 'Creatinine', englishName: 'Creatinine', koreanName: '크레아티닌' },
  { key: 'chloroform', query: 'Chloroform', englishName: 'Chloroform', koreanName: '클로로포름', aliases: ['Trichloromethane'] },
  { key: 'diethyl-ether', query: 'Diethyl ether', englishName: 'Diethyl ether', koreanName: '디에틸에터', aliases: ['Ethoxyethane'] },
  { key: 'dimethyl-sulfoxide', query: 'Dimethyl sulfoxide', englishName: 'Dimethyl sulfoxide', koreanName: '디메틸설폭사이드' },
  { key: 'capsaicin', query: 'Capsaicin', englishName: 'Capsaicin', koreanName: '캡사이신' },
  { key: 'menthol', query: 'Menthol', englishName: 'Menthol', koreanName: '멘톨' },
  { key: 'melatonin', query: 'Melatonin', englishName: 'Melatonin', koreanName: '멜라토닌' },
  { key: 'dopamine', query: 'Dopamine', englishName: 'Dopamine', koreanName: '도파민' },
  { key: 'serotonin', query: 'Serotonin', englishName: 'Serotonin', koreanName: '세로토닌' },
  { key: 'epinephrine', query: 'Epinephrine', englishName: 'Epinephrine', koreanName: '에피네프린', aliases: ['Adrenaline'] },
  { key: 'boric-acid', query: 'Boric acid', englishName: 'Boric acid', koreanName: '붕산' },
  { key: 'borax', query: 'Borax', englishName: 'Borax', koreanName: '붕사', aliases: ['Sodium tetraborate decahydrate'] },
  { key: 'calcium-sulfate', query: 'Calcium sulfate', englishName: 'Calcium sulfate', koreanName: '황산칼슘' },
  { key: 'magnesium-hydroxide', query: 'Magnesium hydroxide', englishName: 'Magnesium hydroxide', koreanName: '수산화마그네슘' },
  { key: 'calcium-hydroxide', query: 'Calcium hydroxide', englishName: 'Calcium hydroxide', koreanName: '수산화칼슘' },
  { key: 'ammonium-chloride', query: 'Ammonium chloride', englishName: 'Ammonium chloride', koreanName: '염화암모늄' },
  { key: 'barium-sulfate', query: 'Barium sulfate', englishName: 'Barium sulfate', koreanName: '황산바륨' },
  { key: 'titanium-dioxide', query: 'Titanium dioxide', englishName: 'Titanium dioxide', koreanName: '이산화티타늄' },
  { key: 'zinc-oxide', query: 'Zinc oxide', englishName: 'Zinc oxide', koreanName: '산화아연' },
] as const

export function getCuratedCompoundPage(page: number, pageSize: number) {
  const targetPage = Math.max(1, page)
  const startIndex = (targetPage - 1) * pageSize
  const endIndex = startIndex + pageSize

  return {
    compounds: CURATED_COMPOUNDS.slice(startIndex, endIndex),
    totalCount: CURATED_COMPOUNDS.length,
    totalPages: Math.ceil(CURATED_COMPOUNDS.length / pageSize),
  }
}
